<a href="https://colab.research.google.com/github/lamyse1/deep-learning-/blob/main/Week7/Dl_Week7_Notebook7_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# AAI612: Deep Learning & its Applications


The CountVectorizer provides a simple way to both tokenize a collection of text documents and build a vocabulary of known words, but also to encode new documents using that vocabulary. You can use it as follows:

* Create an instance of the `CountVectorizer` class.
* Call the `fit()` function in order to learn a vocabulary from one or more documents.
* Call the `transform()` function on one or more documents as needed to encode each as a vector.

An encoded vector is returned with a length of the entire vocabulary and an integer count for the number of times each word appeared in the document. Because these vectors will contain a lot of zeros, we call them sparse. Python provides an efficient way of handling sparse vectors in the scipy.sparse package. The vectors returned from a call to transform() will be sparse vectors, and you can transform them back to NumPy arrays to look and better understand what is going on by calling the toarray() function. Below is an example of using the CountVectorizer to tokenize, build a vocabulary, and then encode a document.

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
# list of text documents
corpus = ["The quick brown fox jumped over the lazy dog."]

### Create the transform

In [5]:
vectorizer = CountVectorizer()

### Tokenize and Build Vocabulary

In [6]:
vectorizer.fit(corpus)

CountVectorizer()

Access the vocabulary to see what exactly was tokenized.  Notice that all words were made lowercase by default and that the punctuation was ignored:

In [7]:
vectorizer.vocabulary_

{'the': 7,
 'quick': 6,
 'brown': 0,
 'fox': 2,
 'jumped': 3,
 'over': 5,
 'lazy': 4,
 'dog': 1}

### Encode the document:

In [8]:
vector = vectorizer.transform(corpus)

### Summarize encoded vector

In [9]:
print(vector.shape)
print(vector.toarray())

(1, 8)
[[1 1 1 1 1 1 1 2]]


### Encode other documents

The same vectorizer can be used on documents that contain words not included in the vocabulary. These words are ignored and no count is given in the resulting vector. For example, below is an example of using the vectorizer above to encode a document with one word in the vocab and one word that is not:

In [10]:
# encode another document
text2 = ["the puppy"]
vector = vectorizer.transform(text2)
print(vector.toarray())

[[0 0 0 0 0 0 0 1]]


## Word Frequencies with TF-IDF

Word counts are a good starting point, but are very basic. One issue with simple counts is that some words like the will appear many times and their large counts will not be very meaningful in the encoded vectors. An alternative is to calculate word frequencies, and by far the most popular method is called TF-IDF. This is an acronym that stands for Term Frequency - Inverse Document Frequency which are the components of the resulting scores assigned to each word.
* **Term Frequency**: This summarizes how often a given word appears within a document.
* **Inverse Document Frequency**: This downscales words that appear a lot across documents.

Without going into the math, `TF-IDF` are word frequency scores that try to highlight words that are more interesting, e.g. frequent in a document but not across documents. The `TfidfVectorizer` will tokenize documents, learn the vocabulary and inverse document requency weightings, and allow you to encode new documents.

Alternately, if you already have a learned CountVectorizer, you can use it with a `TfidfTransformer` to just calculate the inverse document frequencies and start encoding documents. The same `create, fit, and transform` process is used as with the `CountVectorizer`.

### List of text documents

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = ["The quick brown fox jumped over the lazy dog.", "The dog.", "The fox"]

### Create the transform

In [12]:
vectorizer = TfidfVectorizer()

### Tokenize and build vocab

In [13]:
vectorizer.fit(corpus)

TfidfVectorizer()

### Summarize

In [14]:
print(vectorizer.vocabulary_)
print(vectorizer.idf_)

{'the': 7, 'quick': 6, 'brown': 0, 'fox': 2, 'jumped': 3, 'over': 5, 'lazy': 4, 'dog': 1}
[1.69314718 1.28768207 1.28768207 1.69314718 1.69314718 1.69314718
 1.69314718 1.        ]


### Encode document

In [15]:
vector = vectorizer.transform([corpus[0]])


### Summarize encoded vector

In [16]:
print(vector.shape)
print(vector.toarray())

(1, 8)
[[0.36388646 0.27674503 0.27674503 0.36388646 0.36388646 0.36388646
  0.36388646 0.42983441]]


A vocabulary of 8 words is learned from the documents and each word is assigned a unique integer index in the output vector. The inverse document frequencies are calculated for each word in the vocabulary, assigning the lowest score of 1.0 to the most frequently observed word: the at index 7. Finally, the first document is encoded as an 8-element sparse array and we can review the final scorings of each word with different values for the, fox, and dog from the other words in the vocabulary.  The scores are normalized to values between 0 and 1 and the encoded document vectors can
then be used directly with most machine learning algorithms.

## Corpus Modification : Instead of the original animal-themed corpus, I created a new corpus of movie reviews.


In [17]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# Original Example: Animal-themed Corpus
print("=== Original Corpus ===")
original_corpus = [
    "The quick brown fox jumped over the lazy dog.",
    "The dog.",
    "The fox"
]

# Demonstrate CountVectorizer
print("\n=== CountVectorizer Example ===")
count_vectorizer = CountVectorizer()
count_vectorizer.fit(original_corpus)

print("Vocabulary:")
print(count_vectorizer.vocabulary_)



=== Original Corpus ===

=== CountVectorizer Example ===
Vocabulary:
{'the': 7, 'quick': 6, 'brown': 0, 'fox': 2, 'jumped': 3, 'over': 5, 'lazy': 4, 'dog': 1}


In [18]:
# Transform and print the vectors
original_count_vector = count_vectorizer.transform(original_corpus)
print("\nCount Vectors:")
print(original_count_vector.toarray())

# Modified Example: Movie Review Corpus
print("\n=== Modified Corpus: Movie Reviews ===")
movie_corpus = [
    "The action movie was exciting and fast-paced.",
    "A brilliant performance by the lead actor.",
    "Slow pacing made the movie less enjoyable.",
    "Incredible special effects and thrilling scenes."
]

# Demonstrate TF-IDF Vectorization on the new corpus
tfidf_vectorizer = TfidfVectorizer()
tfidf_vectorizer.fit(movie_corpus)

print("Vocabulary:")
print(tfidf_vectorizer.vocabulary_)

print("\nInverse Document Frequencies (IDF):")
# Create a dictionary of words and their IDF scores
idf_dict = {word: score for word, score in zip(tfidf_vectorizer.get_feature_names_out(), tfidf_vectorizer.idf_)}
for word, idf in sorted(idf_dict.items(), key=lambda x: x[1]):
    print(f"{word}: {idf:.2f}")




Count Vectors:
[[1 1 1 1 1 1 1 2]
 [0 1 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 1]]

=== Modified Corpus: Movie Reviews ===
Vocabulary:
{'the': 20, 'action': 0, 'movie': 13, 'was': 22, 'exciting': 7, 'and': 2, 'fast': 8, 'paced': 14, 'brilliant': 3, 'performance': 16, 'by': 4, 'lead': 10, 'actor': 1, 'slow': 18, 'pacing': 15, 'made': 12, 'less': 11, 'enjoyable': 6, 'incredible': 9, 'special': 19, 'effects': 5, 'thrilling': 21, 'scenes': 17}

Inverse Document Frequencies (IDF):
the: 1.22
and: 1.51
movie: 1.51
action: 1.92
actor: 1.92
brilliant: 1.92
by: 1.92
effects: 1.92
enjoyable: 1.92
exciting: 1.92
fast: 1.92
incredible: 1.92
lead: 1.92
less: 1.92
made: 1.92
paced: 1.92
pacing: 1.92
performance: 1.92
scenes: 1.92
slow: 1.92
special: 1.92
thrilling: 1.92
was: 1.92


In [19]:
# Transform the first movie review
first_movie_review_vector = tfidf_vectorizer.transform([movie_corpus[0]])
print("\nTF-IDF Vector for first review:")
print(first_movie_review_vector.toarray())

# Additional Preprocessing Demonstration
print("\n=== Additional Preprocessing Options ===")
# Using stop_words to remove common words
stopwords_vectorizer = TfidfVectorizer(stop_words='english')
stopwords_vectorizer.fit(movie_corpus)

print("Vocabulary (with stop words removed):")
print(stopwords_vectorizer.vocabulary_)




TF-IDF Vector for first review:
[[0.387766   0.         0.30571917 0.         0.         0.
  0.         0.387766   0.387766   0.         0.         0.
  0.         0.30571917 0.387766   0.         0.         0.
  0.         0.         0.24750601 0.         0.387766  ]]

=== Additional Preprocessing Options ===
Vocabulary (with stop words removed):
{'action': 0, 'movie': 9, 'exciting': 5, 'fast': 6, 'paced': 10, 'brilliant': 2, 'performance': 12, 'lead': 8, 'actor': 1, 'slow': 14, 'pacing': 11, 'enjoyable': 4, 'incredible': 7, 'special': 15, 'effects': 3, 'thrilling': 16, 'scenes': 13}


In [20]:
# Limiting vocabulary size
limited_vocab_vectorizer = TfidfVectorizer(max_features=5)
limited_vocab_vectorizer.fit(movie_corpus)

print("\nVocabulary (limited to top 5 features):")
print(limited_vocab_vectorizer.vocabulary_)


Vocabulary (limited to top 5 features):
{'the': 4, 'action': 0, 'movie': 2, 'and': 1, 'special': 3}
